voting ensembling technique for classifiaction problem

In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("C:\\Users\\Pranjali\\OneDrive\\Desktop\\ml_algorithms\\ensembling_techniques\\voting_ensembling\\Iris.csv")

In [4]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
# removing the id column
df=df.iloc[:,1:]

In [6]:
df.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [7]:
#converting sepices cloumn 
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [8]:
df['Species']=encoder.fit_transform(df['Species'])

In [9]:
df.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0            5.1           3.5            1.4           0.2        0
1            4.9           3.0            1.4           0.2        0
2            4.7           3.2            1.3           0.2        0
3            4.6           3.1            1.5           0.2        0
4            5.0           3.6            1.4           0.2        0

In [25]:
#seprating x and y i.e input and output
x=df.drop("Species",axis=1)
y=df['Species']

In [26]:
x.shape

(150, 4)

In [27]:
y.shape

(150,)

In [28]:
# importing multiple modes for taining the data
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

In [29]:
c1=LogisticRegression(max_iter=1000)
c2=KNeighborsClassifier()
c3=RandomForestClassifier(random_state=42)

In [33]:
score=cross_val_score(c1,x,y,cv=10,scoring="accuracy")
print(np.mean(score))

0.9733333333333334

In [34]:
score=cross_val_score(c2,x,y,cv=10,scoring="accuracy")
print(np.mean(score))

0.9666666666666668

In [35]:
score=cross_val_score(c3,x,y,cv=10,scoring="accuracy")
print(np.mean(score))

0.96

In [37]:
from sklearn.ensemble import VotingClassifier

In [40]:
voting = VotingClassifier(
    estimators=[
        ('lr', c1),
        ('knn', c2),
        ('rf', c3)
    ],
    voting='soft'# used to take the majority outcome
)

In [41]:
# checking the accuracy of voting classfier after combining the all 3 algortihms 
score=cross_val_score(voting,x,y,cv=10,scoring="accuracy")
print(np.mean(score))

0.96

there are 2 types of voting hard and soft
hard(suitalbe for category ,gives the majority)=accracy:97
soft(suitalbe for numeric data grive the avg,probalities)=accuracy:96